### ISSUE TITLE
Asset linking issue with sprockets-rails

### ISSUE THREAD

**Issue by tarebyte** [github/octicons#50]
I'm currently using octicons with bower in the Rails asset pipeline with `sprockets-octicons`, I updated sprocket-rails to `2.3.0` and now I have the following issue

```
Asset was linked to from an alias rather than its exact path. Alias resolving may not be available in production.
Use "octicons/octicons/octicons.eot" instead of "octicons.eot"
```

I changed `sprockets-octicons.scss` to
```scss
@font-face {
  font-family: 'octicons';
  src: font-url('octicons/octicons/octicons.eot?#iefix') format('embedded-opentype'),
         font-url('octicons/octicons/octicons.woff') format('woff'),
         font-url('octicons/octicons/octicons.ttf') format('truetype'),
         font-url('octicons/octicons/octicons.svg#octicons') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

And it works again, but I don't know if that's a good final solution. I'd be happy to make a PR to help out though!
